### PR TITLE
Pluggable JSON Serialization and Logging

### PR DESCRIPTION
**Pull request by andyday**
I currently use ServicesStack.Text for JSON Serialization and I know others who prefer Newtonsoft.Json.  I've added the ability to customize the provider used.

During development and debugging, I find it helpful to log the token JSON during encode and decode.  I've also added the ability to configure a Log method if logging is desired.

### CODE REVIEW

**Comment by abatishchev** [comment]
You may want to squash/combine commits into 1, or something like this.

**Comment by devinrader** [comment]
I actually prefer this design over switching outright to and taking the dependency on JSON.NET which brings it own set of problems with it.  If you look at the history of the library JSON.NET was actually deliberately removed as a dependency a while ago.

@andyday we actually have tests now :astonished: so it would be awesome if you could pull those down and make sure they continue to pass and add where needed for this PR.

**Comment by andyday** [comment]
@abatishchev you can see the summary of the change under the Files Changed tab.  there should be now need to consolidate commits.

**Comment by abatishchev** [comment]
The point is to do not have multiple commits in the repo history, especially if later fixes problems cause but former.

**Comment by andyday** [comment]
@abatishchev point taken.  I'll consolidate and add unit tests...

**Comment by abatishchev** [comment]
Maybe rather than adding an interface, use `Func<string, object>` and `Func<object, string>`?

The very important reason to do not use System.Web.dll's JavaScriptSerializer is its problem with portability and future support of .NET Core. Completely unnecessary and importable dependency.

**Comment by andyday** [comment]
I had thought about that.  Have a Serialize and Deserialize static property...  

Yes I'm not a fan of JavaScriptSerializer nor JSON.NET for that matter.  ServiceStack.Text has been a pleasure to use...  One particular point as it relates to JWT is its default handling of null properties by removing them from the serialized JSON.  This is helpful in reducing the token size.

**Comment by abatishchev** [comment]
I never had issues with Json.Net and from my experience it has been a pleasure to use as well.

Plus ASP.NET Web API depends on it so using another Json serializer doesn't makes sense in this case.

**Comment by andyday** [comment]
I don't use ASP.NET Web API.  I use ServiceStack.  My biggest issue with JSON.NET is its default handling of dates (although its been awhile since I've used it and this problem may have been rectified).

**Comment by devinrader** [comment]
@abatishchev @andyday this conversation is exactly why we just need a mechanism that allows the user to override the default Json serializer.  JavaScriptSerializer will continue to be the default option since its available out of the box on all of the platforms that we want to support and does a good enough job for most users.

Regarding the comment about JSON.NET supporting portability, there are actually much bigger issues there than just JSON serialization as System.Security.Cryptography is not available as a portable library.  There is a version of JWT that I built in the portable branch of this repo if you want to take a look.  I ended up taking a dependency on PCLCrypto to replace the crypto capabilities.

**Comment by devinrader** [comment]
Also @andyday I'm not sure that we should add logging directly to the JWT class.  Instead why not make the Serialize/Deserialize methods virtual and if a user wants to inject some type of logging of the serislized values, they can override them.

**Comment by andyday** [comment]
this has moved to #25

**Pull request closed without merging**
