### PR TITLE
Made Decoder, Serializer to accept Type. Added PayloadType to JwtAuthenticationOptions.

### LINKED ISSUE #374: Unable to parse JWT Token handle data type other than String
Here is the payload of my JWT token:

```json
{
  "jti": "c1c391b5-0fb0-4a98-b536-5591628b9ce4",
  "iss": "JwtAuthDemo",
  "sub": "will",
  "exp": 1644680710,
  "nbf": 1644678910,
  "iat": 1644678910,
  "roles": [
    "Admin",
    "Users"
  ],
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "will"
}
```

The `roles` is an array. This is used for ASP.NET Core `Roles`. If I want to use this, I can't parse this type of JWT Token. I'll get the following error:

```log
info: JWT.Extensions.AspNetCore.JwtAuthenticationHandler[2]
      Error decoding JWT: Unexpected character encountered while parsing value: [. Path 'roles', line 1, position 139., returning failure
      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'roles', line 1, position 139.
         at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
         at Newtonsoft.Json.JsonTextReader.ReadAsString()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
         at JWT.Serializers.JsonNetSerializer.Deserialize[T](String json)
         at JWT.JwtDecoder.DecodeToObject[T](JwtParts jwt, Byte[][] keys, Boolean verify)
         at JWT.JwtDecoderExtensions.DecodeToObject[T](IJwtDecoder decoder, String token, Byte[][] keys, Boolean verify)
         at JWT.JwtDecoderExtensions.DecodeToObject[T](IJwtDecoder decoder, String token, String[] keys, Boolean verify)
         at JWT.Extensions.AspNetCore.JwtAuthenticationHandler.GetAuthenticationResult(String header)
info: JWT.Extensions.AspNetCore.JwtAuthenticationHandler[7]
      Bearer was not authenticated. Failure message: Unexpected character encountered while parsing value: [. Path 'roles', line 1, position 139.
```

> https://github.dev/jwt-dotnet/jwt/blob/20378ec58608119b08f7d199fb4064f2d1b0fab1/src/JWT.Extensions.AspNetCore/JwtAuthenticationHandler.cs#L120

### PR DESCRIPTION
**Pull request by abatishchev**
Resolves #374.

### CODE REVIEW

**Comment by abatishchev** [comment]
@doggy8088 please try the packages (both JWT and JWT.Extensions.AspNetCore) produced by [this build](https://abatishchev.visualstudio.com/OpenSource/_build/results?buildId=960&view=artifacts&pathAsName=false&type=publishedArtifacts) once it's complete and let me know.

**Comment by doggy8088** [comment]
Here is my implementation.  It works.

`Program.cs`

```cs
builder.Services.AddSingleton<IIdentityFactory, CustomIdentityFctory>();

builder.Services.AddAuthentication(options =>
    {
        options.DefaultAuthenticateScheme = JwtAuthenticationDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = JwtAuthenticationDefaults.AuthenticationScheme;
    })
    .AddJwt(options =>
    {
        options.PayloadType = typeof(Dictionary<string, object>);
        options.Keys = new string[] { builder.Configuration.GetValue<string>("JwtSettings:SignKey") };
        options.VerifySignature = true;
    });
```

`CustomIdentityFactory.cs`

```cs
using System.Security.Claims;
using System.Security.Principal;
using JWT.Extensions.AspNetCore;
using JWT.Extensions.AspNetCore.Factories;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;

internal class CustomIdentityFactory : IIdentityFactory
{
    private readonly IOptionsMonitor<JwtAuthenticationOptions> _options;

    public CustomIdentityFactory(IOptionsMonitor<JwtAuthenticationOptions> options) =>
        _options = options;

    public IIdentity CreateIdentity(Type type, object payload)
    {
        var data = payload as Dictionary<string, object>;
        IEnumerable<Claim> claims = GetClaims(data);
        return _options.CurrentValue.IncludeAuthenticationScheme ?
            new ClaimsIdentity(claims, JwtAuthenticationDefaults.AuthenticationScheme) :
            new ClaimsIdentity(claims);
    }

    private IEnumerable<Claim> GetClaims(Dictionary<string, object>? payload)
    {
        if (payload == null)
        {
            yield break;
        }
        foreach (var p in payload)
        {
            if (p.Value is String value)
            {
                yield return new Claim(p.Key, value);
            }
            if (p.Value is JToken arr)
            {
                foreach (var item in arr.Values<string>())
                {
                    yield return new Claim(p.Key, item);
                }
            }
        }
    }
}
```

**Comment by doggy8088** [comment]
You can see my sample project here: https://github.com/doggy8088/AspNetCore6JwtNetAuthN/tree/support-roles

> The `support-roles` branch.

**Comment by abatishchev** [comment]
Awesome news. Thanks for confirming it worked! I'll see if I want to refactor the current PR little more or will do that in another one. Will publish the beta versions of the packages shortly after.

**Comment by doggy8088** [comment]
@abatishchev I think my implementation is compatible with current `v8` version. You might considering treat it as `DefaultIdentityFactory`.

**Comment by abatishchev** [comment]
@doggy8088 no, I don't think it is. Handler uses a newly added method `DecodeToObject(Type, string, string[]`.

**Pull request merged**
