### PR TITLE
Removing static API

### PR DESCRIPTION
**Pull request by nbarbettini**
Rebased #103

### CODE REVIEW

**Comment by nbarbettini** [comment]
@abatishchev I noticed you removed these files: https://github.com/jwt-dotnet/jwt/blob/master/tests/JWT.Tests.NETFramework/DecodeTests.cs

These tests aren't duplicated anywhere else. I think maybe we should change them to using the instance (not static), instead of deleting them?

**Comment by abatishchev** [comment]
So did I :-D Never mind, closed that PR in favor of this one.

Regarding the tests. IIRC, new tests are just clones of old tests except the part where static factory is assigned to substitute JSON (de)serializer. So we should be fine by deleting them. An additional review by separate pair of eyes would be helpful though!

**Comment by abatishchev** [comment]
Oops, closed wrong one. Reopened.

**Comment by nbarbettini** [comment]
Re: tests - I agree that the duplicate tests in `JWT.Tests.Core` are unnecessary and can be deleted. However, the tests in `JWT.Tests.NETFramework` were testing the other deserializer plugins and may still be useful. Do you want to keep the System.Web and ServiceStack tests around?

**Comment by abatishchev** [comment]
Frankly I don't. This functionality goes away with the removal of static API.
To add it back and this time do it properly, there should be 2 additional/separate nuget packages (as per #76) with their own tests. Those might be just clones of standard tests but targeted against their own implementation.
Makes sense?

**Comment by nbarbettini** [comment]
Ah, now I'm understanding you. Yep! Let's merge.

**Comment by abatishchev** [comment]
Pushed to NuGet as [3.0.0-beta3](https://www.nuget.org/packages/JWT/3.0.0-beta3).

@nbarbettini Thanks for your help! As always :)

**Pull request merged**
