### PR TITLE
Added a Table of Contents on the README.md

### PR DESCRIPTION
**Pull request by hartmark**
used the program pandoc:
pandoc -s --toc README.md -o README.md
https://pandoc.org/index.html

### CODE REVIEW

**Comment by abatishchev** [comment]
It broke some of the markdown markup (no pun intended) :( in the very beginning, sponsor's banner, also the toc itself. You can see if you open the file in the preview mode when it'll render the markdown.

**Comment by abatishchev** [comment]
Would it be easier to add the toc by hand? The idea I like, the only precondition is to not break the markup which looks fine otherwise

**Comment by hartmark** [comment]
Hmm, the diff looks like the whole file was changed. I'll check again when I get time after the weekend probably. I think I have setup my diff to ignore whitespace differences.

**Comment by hartmark** [comment]
Where on the page do you want the TOC? Just in top or under the sponsor?

**Comment by hartmark** [comment]
Reverted all whitespace changes from pandoc and just kept the TOC.

**Comment by abatishchev** [comment]
Sorry for coming late to the PR. The concern I have is in the resulting markup:

image

**Comment by hartmark** [comment]
I fixed the markup now with using the tool doctoc instead

It's installed easily by just:
` install -g doctoc`

And then to re-create toc you can just issue:
`doctoc README.md`

**Comment by abatishchev** [comment]
Cool, thanks! Do you know if it can not to insert itself into the title, I mean not add "by DocToc"? Otherwise looks good.

**Comment by hartmark** [comment]
It seems to look for just the comment, so I guess it's safe to remove the by doctoc link.

https://github.com/thlorenz/doctoc#update-existing-doctoc-tocs-effortlessly

**Comment by abatishchev** [comment]
What doesn't both me is this:

```
!-- START doctoc generated TOC please keep comment here to allow auto update -->
<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->
```

What does is this:

```
**Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*
```

Do you know if then can stop self-advertizing this way?

**Comment by hartmark** [comment]
If I removed that line the self-promotion didn't get generated back if I rerun doctoc tool

**Comment by hartmark** [comment]
I have pushed an update with the advertising removed now

**Review by abatishchev — APPROVED** [review]

**Comment by abatishchev** [comment]
Thanks you, sir!

**Pull request merged**
