### PR TITLE
Add support for ECDSA signing algorithms

### PR DESCRIPTION
**Pull request by simon-pearson**
An initial stab at #304.

A few points of discussion:
- The implementation of the `ECDSAAlgorithm` class relies heavily on the [`ECDsa.SignData`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsa.signdata?view=net-5.0), [`ECDsa.VerifyData`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsa.verifydata?view=net-5.0), [`ECDsaCertificateExtensions.GetECDsaPublicKey()`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.ecdsacertificateextensions.getecdsapublickey) and [`ECDsaCertificateExtensions.GetECDsaPrivateKey()`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.ecdsacertificateextensions.getecdsaprivatekey) methods, all of which were introduced in .NET Standard 1.4.  Our only target >= .NET Standard 1.4 is .NET Standard 2.0, so I've excluded this class from the build in all targets except .NET Standard 2.0.
- If the `ECDSAAlgorithmFactory.Create` method is called in any target other than .NET Standard 2.0 it throws `NotImplementedException`.
- Possibly we could re-work the preprocessor directives to include the `ECDSAAlgorithm`/`ES256Algorithm`/`ES384Algorithm`/`ES512Algorithm` classes in other targets but make them throw if you call any public methods on them.  Is there merit to this?

As always this is just a starter, feel free to chop + change as you see fit 👍

### CODE REVIEW

**Review by abatishchev — APPROVED** [review]

**Comment by abatishchev** [comment]
@simon-pearson awesome!! i've bumped the version to `8.1.0-beta1` and ready to ship it.

**Comment by abatishchev** [comment]
Just an idea for a separate PR, to improve tests: right now there is a test class for each algorithm and they all are identical in other than the algorithm type. We can leverage MSTest2's `[DataTestMethod]`:

```csharp
[DynamicData(nameof(GetData), DynamicDataSourceType.Method)]
[DataTestMethod]
public void Test(string str, Foo foo)
{
}

// this signature must stay
private static IEnumerable<object[]> GetData()
{
    // the number of objects must match the parameters
    yield return new object[]
    {
        "foo",
        new Foo()
    };
    yield return new object[]
    {
        "bar",
        new Bar()
    };
}
```
See if the same set of tests can accept different algorithm objects?

**Comment by abatishchev** [comment]
Released as [8.1.0-beta1](https://www.nuget.org/packages/JWT/8.1.0-beta1). Let's promote it to a release in a week or two, if there will be no complains.

**Comment by abatishchev** [comment]
Thanks you so much for both contributions!! You've made a huge difference in a very short period of time.

**Comment by k15tfu** [comment]
> * The implementation of the `ECDSAAlgorithm` class relies heavily on the [`ECDsa.SignData`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsa.signdata?view=net-5.0), [`ECDsa.VerifyData`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsa.verifydata?view=net-5.0), [`ECDsaCertificateExtensions.GetECDsaPublicKey()`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.ecdsacertificateextensions.getecdsapublickey) and [`ECDsaCertificateExtensions.GetECDsaPrivateKey()`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.ecdsacertificateextensions.getecdsaprivatekey) methods, all of which were introduced in .NET Standard 1.4.  Our only target >= .NET Standard 1.4 is .NET Standard 2.0, so I've excluded this class from the build in all targets except .NET Standard 2.0.

@simon-pearson Hi! Just curious how did you check it? As far as I can see all of these four methods
* [`ECDsa.SignData(Byte[], HashAlgorithmName)`](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsa.signdata?view=netframework-4.6.1#system-security-cryptography-ecdsa-signdata(system-byte()-system-security-cryptography-hashalgorithmname)) ,
* [`ECDsa.VerifyData(Byte[], Byte[], HashAlgorithmName)`](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsa.verifydata?view=netframework-4.6.1#system-security-cryptography-ecdsa-verifydata(system-byte()-system-byte()-system-security-cryptography-hashalgorithmname)) ,
* [`ECDsaCertificateExtensions.GetECDsaPublicKey(X509Certificate2)`](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.ecdsacertificateextensions.getecdsapublickey?view=netframework-4.6.1) ,
* and [`ECDsaCertificateExtensions.GetECDsaPrivateKey(X509Certificate2)`](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.ecdsacertificateextensions.getecdsaprivatekey?view=netframework-4.6.1)


were introduced in .NET Framework 4.6.1 (see links), but not .NET Standard 1.4. Probably it worth considering upgrading the minimum target framework to net461 (or even newer) in the project, because otherwise these algorithms will not be available on the latest versions of the .NET Framework.

**Pull request merged**
