### PR TITLE
Adding IAlgFactory to master (v3) branch

### PR DESCRIPTION
**Pull request by abatishchev**
Copying changes from #101

### CODE REVIEW

**Comment by djavier** [comment]
@abatishchev the current stable Nuget version `2.4.0` does not include the latest `IAlgorithmFactory` changes.

**Comment by abatishchev** [comment]
Oh, really? How could it happen? Hmm. I'll replace it tomorrow with the right assembly. Sorry about this.

**Comment by abatishchev** [comment]
@djavier this has been fixed, [2.4.1](https://www.nuget.org/packages/JWT/2.4.1) is release, 2.4.0 is unlisted. Thanks for reporting!

**Comment by abatishchev** [comment]
@blgrnboy Thanks for reviewing! I tried to check-in but GitHub settings if require a review than require by a member (@nbarbettini). Let's wait him to come back and review, I'll check-in shortly thereafter.

**Comment by djavier** [comment]
Thank you for your quick responses.

**Comment by abatishchev** [comment]
Meanwhile I published this as [3.0.0-beta2](https://www.nuget.org/packages/JWT/3.0.0-beta2)

**Comment by abatishchev** [comment]
@nbarbettini hey Nate, please take a look to let it in.

**Comment by nbarbettini** [comment]
Looks good 👍 sorry for the delay @abatishchev.

**Pull request merged**
