### PR TITLE
Pin cake version

### PR DESCRIPTION
**Pull request by nbarbettini**
Pinning the version of cake used, to avoid any changes that might occur if cake is updated. (see [here](http://cakebuild.net/docs/tutorials/pinning-cake-version))

### CODE REVIEW

**Comment by nbarbettini** [comment]
This is still failing. Looking at the AppVeyor logs, the errors started today. Unless something changed in the AppVeyor configuration, my guess is that it's a service issue.

**Comment by nbarbettini** [comment]
Ah, it's this: https://appveyor.statuspage.io/incidents/m2vdvw39kdk8

**Comment by abatishchev** [comment]
Oh, ok, let's wait once they're fully up

**Comment by StefH** [comment]
My suggestion is to drop cake and just build your code using a different approach in AppVeyor.

I also build several project using AppVeyor. Just take a look at https://github.com/StefH/System.Linq.Dynamic.Core or other projects from me on github.

**Comment by nbarbettini** [comment]
This issue isn't specific to cake - AppVeyor is having trouble restoring any NuGet package right now (AFAIK).

**Comment by StefH** [comment]
Indeed some issues:

```
dotnet restore src\System.Linq.Dynamic.Core\System.Linq.Dynamic.Core.csproj
  Restoring packages for C:\projects\system-linq-dynamic-core\src\System.Linq.Dynamic.Core\System.Linq.Dynamic.Core.csproj...
  Failed to download package 'NetLegacySupport.Action.1.1.1' from 'https://www.nuget.org/api/v2/package/NetLegacySupport.Action/1.1.1'.
  The download of 'https://www.nuget.org/api/v2/package/NetLegacySupport.Action/1.1.1' timed out because no data was received for 60000ms.
```
Maybe related to the new preview server for nuget : https://preview.nuget.org

**Comment by abatishchev** [comment]
This worked fine today: https://ci.appveyor.com/project/abatishchev/jwt/build/1.0.128
This hanged again it seems: https://ci.appveyor.com/project/abatishchev/jwt/build/1.0.129

**Comment by nbarbettini** [comment]
@abatishchev Can you restart this build on AV? Looks like they've resolved these issues: http://status.appveyor.com/incidents/m2vdvw39kdk8

**Pull request merged**
