### PR TITLE
Addressed issue #43 should provide algorithm when decoding/verifying.

### PR DESCRIPTION
**Pull request by vincentparrett**
This pr addresses https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/ - however it is an interface breaking change. That said, it's a very small breaking change, and simple to resolve.

### CODE REVIEW

**Comment by mfriscia7** [comment]
You should also add changes to README.md to reflect these changes

**Comment by abatishchev** [comment]
Contribution is always welcome!

**Comment by abatishchev** [comment]
Can you please rebase on the latest?

**Comment by abatishchev** [comment]
Can you please rebase on the latest?

**Comment by vincentparrett** [comment]
I tried but there were so many changes in the latest it was a merge nightmare. I will try and find the time to redo this PR.

**Comment by abatishchev** [comment]
Please, appreciate your contribution!

**Comment by abatishchev** [comment]
Can you please redo this? I'll be happy to merge and release.

**Comment by abatishchev** [comment]
Can you please create a new branch based on the v2 codebase? Thanks!

**Comment by abatishchev** [comment]
Abandoning this since the static API is obsolete and will be removed. New instance-based API doesn't have this issue since you would specify the algorithm explicitly by type.

**Pull request closed without merging**
