### PR TITLE
Removes the expected signature from the SignatureVerificationException for security reasons

### PR DESCRIPTION
**Pull request by rpetz**
Resolves issue #61

### CODE REVIEW

**Review by abatishchev — CHANGES_REQUESTED** [review]
Can you store those two variables into Exception.Data dictionary, please? This would help during debugging still but without disclosure.

**Review by rpetz — COMMENTED** [review]
Requested information added into the exception's data dictionary

**Comment by abatishchev** [comment]
Can you please make one more change. Bump the version at https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/Properties/AssemblyInfo.cs to 1.4.0? So I could build and push to nuget right from the latest master. Thanks!

**Review by rpetz — COMMENTED** [review]
Version bump to 1.4.0

**Review by abatishchev — APPROVED** [review]

**Comment by abatishchev** [comment]
Thanks a bunch! I'll try to publish as soon as I get access to my laptop. If won't happen in while, please please remind.

**Comment by rpetz** [comment]
awesome, thanks for the quick responses 👍

**Comment by rpetz** [comment]
> Thanks a bunch! I'll try to publish as soon as I get access to my laptop. If won't happen in while, please please remind.

Apologies - here's your belated reminder =P

[ Joking - hope it made you chuckle! ]

**Comment by abatishchev** [comment]
Oh, wow. A blast from the past :-D

**Pull request merged**
