### PR TITLE
Made secret optional in Decode() to support asymmetric algorithms

### PR DESCRIPTION
**Pull request by abatishchev**
Continuation of #258, cc @stefansolid.

* Made secret optional in Decode() to support asymmetric algorithms
* Bumped version to 6.1.2

### CODE REVIEW

**Comment by abatishchev** [comment]
@stefensolid please take a look and try [this build](https://abatishchev.visualstudio.com/OpenSource/_build/results?buildId=407&view=artifacts&type=publishedArtifacts)'s drop, see if resolves the rest of your issues.

**Comment by stefansolid** [comment]
Now the builder can run MustVerifySignature if the cert is the private cert. 

However, when I on the client uses the MustVerifySignature and only providing the public cert I get the same exception (Exception thrown: 'System.InvalidOperationException' in JWT.dll)

So almost there :)

**Comment by abatishchev** [comment]
The library verified the signature by creating it and comparing with the original. And for that you need the private key. Because if you could do that with having only the public key then you could forge the signature and defeat the whole security mechanism of JWT. So the need to have the private key sounds like by design to me.

**Comment by stefansolid** [comment]
Seems logically, I admit this is not my strongest of skills. I just took my JWT created and posted it on jwt.io where there was a box to enter "Public Key or Certificate. Enter it in plain text only if you want to verify a token". So it was from that I got idea that token could be verified with public key.

**Comment by abatishchev** [comment]
Hmm, you're right. I see you [can do it](https://stackoverflow.com/questions/34403823/verifying-jwt-signed-with-the-rs256-algorithm-using-public-key-in-c-sharp) in C# too. But differently than the library is doing it today.
Let me finish this PR and I'll be working to make it possible.

**Comment by stefansolid** [comment]
Seems to work just perfect now! My client loads the public cert and passes validation without exception. Server-side uses the private cert for creation and validation of tokens.

**Comment by abatishchev** [comment]
Perfect! Thanks for the confirmation. I'm merging it now.

**Pull request merged**
