### PR TITLE
Fix tests nuget references

### PR DESCRIPTION
**Pull request by blgrnboy**
Fixed nuget references

### CODE REVIEW

**Comment by blgrnboy** [comment]
Something is odd here.  AppVeyor doesn't seem to be able to find the packages now, but I can in my local VS 2017 environment..  Perhaps the build process is configured to look for packages in the previous location?

**Comment by nbarbettini** [comment]
I think I know what's going on here. I inadvertently screwed something up in my previous PR. This won't quite fix it, because (as you noticed) it breaks the CI build on AppVeyor. I think I know how to fix it; I'll take a look.

**Comment by blgrnboy** [comment]
Thanks!

**Comment by abatishchev** [comment]
Hey @nbarbettini did you have a chance to take a look? Currently it works either locally or on the build server

**Comment by nbarbettini** [comment]
@abatishchev Haven't had a chance to look yet sorry, will look at it soon.

**Pull request closed without merging**
