### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by abatishchev**
Adds C# highlighting where applicable. Minor updates in code.

### CODE REVIEW

**Comment by devinrader** [comment]
Looks like a lot of the lines are actually unchanged.  Did you convert tabs to spaces, or change line endings?  If not can you revert and submit a PR that has only the specific lines that were added or changed?

**Comment by abatishchev** [comment]
Hm. Not actually. I was using GitHub web editor. This is how it highlight the changes when indents were changed (```csharp instead of 4 spaces). Does it make sense?

**Comment by devinrader** [comment]
OK..I got you now.

Thanks for the PR.

**Comment by devinrader** [comment]
Derp...have to actually confirm the merge in order for it to be merged.  :stuck_out_tongue_closed_eyes:

**Comment by abatishchev** [comment]
Yeah, I noticed the same. Looks merged now :) Thanks!

**Pull request merged**
