### PR TITLE
Fixed tests, build on Arch Linux

### PR DESCRIPTION
**Pull request by hartmark**
Will probably be needed for #407 

Unless this fix is applied the tests fail with this error when running on arch linux:

```
Test method JWT.Tests.Algorithms.RSAlgorithmTests.Ctor_Should_Throw_Exception_When_PrivateKey_Is_Null threw exception: 
AutoFixture.ObjectCreationExceptionWithPath: AutoFixture was unable to create an instance from System.Security.Cryptography.RSACryptoServiceProvider because creation unexpectedly failed with exception. Please refer to the inner exception to investigate the root cause of the failure.

Request path:
	System.Security.Cryptography.RSACryptoServiceProvider

Inner exception messages:
	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	  System.Security.Cryptography.CryptographicException: Specified key is not a valid size for this algorithm.

 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Security.Cryptography.CryptographicException: Specified key is not a valid size for this algorithm.
    at System.Security.Cryptography.AsymmetricAlgorithm.set_KeySize(Int32 value)
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.set_KeySize(Int32 value)
   at System.Security.Cryptography.RSACryptoServiceProvider.set_KeySize(Int32 value)
--- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.InvokeOneParameter(Object obj, BindingFlags invokeAttr, Binder binder, Object parameter, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at AutoFixture.Kernel.AutoPropertiesCommand`1.Execute(Object specimen, ISpecimenContext context)
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
   at AutoFixture.AutoPropertiesTarget.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
--- End of inner exception stack trace ---
    at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
   at AutoFixture.Fixture.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.SpecimenContext.Resolve(Object request)
   at AutoFixture.Kernel.SeedIgnoringRelay.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
   at AutoFixture.AutoPropertiesTarget.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
   at AutoFixture.Fixture.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.SpecimenContext.Resolve(Object request)
   at AutoFixture.SpecimenFactory.Create[T](ISpecimenContext context)
   at AutoFixture.SpecimenFactory.Create[T](ISpecimenBuilder builder)
   at JWT.Tests.Algorithms.RSAlgorithmTests.get_RSACryptoServiceProvider() in /home/markus/code/jwt/tests/JWT.Tests.Common/Algorithms/RSAlgorithmTests.cs:line 21
   at JWT.Tests.Algorithms.RSAlgorithmTests.Ctor_Should_Throw_Exception_When_PrivateKey_Is_Null(Func`3 algFactory) in /home/markus/code/jwt/tests/JWT.Tests.Common/Algorithms/RSAlgorithmTests.cs:line 41

```

### CODE REVIEW

**Comment by abatishchev** [comment]
Can you help me understand, if you know, the cause for the issue?

> System.Security.Cryptography.CryptographicException: Specified key is not a valid size for this algorithm.

Why? I mean is there a size that is valid for this algorithm? Should it be smaller (idk if it can be) or larger (shall we try)?

**Comment by abatishchev** [comment]
Looks like the provided secret is too short indeed. It must be 128 bit long, or 256 etx. I don't know why it works on other platforms though, maybe they're aren't that reactive/picky.

**Comment by hartmark** [comment]
I haven't used AutoFixture so I have no idea how to set the key size

**Comment by abatishchev** [comment]
Right, the issue is in AutoFixture that instantiates RSACryptoServiceProvider with a key length or doesn't like.

If just `new RSACryptoServiceProvider()` works on .NET 6, doesn't it work elsewhere too?

**Comment by hartmark** [comment]
I was conservative with the changes as it was already running on Linux for versions below .net6

I can try change it so all get same behaviour instead if it works

**Comment by hartmark** [comment]
It seems that just newing up RSACryptoServiceProvider is working for all .net versions so I have updated the code.

**Review by abatishchev — APPROVED** [review]

**Comment by abatishchev** [comment]
I approved. Please see if you can check it in after the gated build has succeeded.

**Comment by hartmark** [comment]
Should be alright now :)

**Review by abatishchev — APPROVED** [review]

**Comment by abatishchev** [comment]
Thank you, sir!

**Pull request merged**
