### PR TITLE
Removed referencing System.Text.Json when targeting modern .NET

### LINKED ISSUE #496: System.Text.Json should only be a dependency for .NET standard
**Describe the problem you are trying to solve.**
I do not want STJ listed as a dependency for net 6

**Available workarounds**
Accept un-necessary dependency

**Additional context**
N/a

### PR DESCRIPTION
**Pull request by thompson-tomo**
## Description

Resolves #496.

This removes System.Text.Json as a dependency for dotnet 6 due to it being natively provided by the framework hence the explicit dependency is not need for that TFM.

## Checklist

- <s>[ ] Tests added</s>
- [x] Version bumped
- [x] Changelog updated

### CODE REVIEW

**Comment by abatishchev** [comment]
Can you cite any docs which would confirm that STJ is available without referencing it? If it is then which version? How to update it in the future, e.g. in case of a security vulnerability?

**Comment by thompson-tomo** [comment]
@abatishchev easiest way to confirm it is look in Visual Studio, and expand out the framework under dependencies and that will reveal what is included in the framework. In the case of security vulnerability this made even easier to manage as when the framework used to compile the application gets a new release of STJ (within the same major), the client applications automatically get provided this based on their framework. Hence less maintenance effort.

**Comment by abatishchev** [comment]
Let me check with the .NET team :) I'll circle back.

**Comment by abatishchev** [comment]
Spoke to the .NET team, was told this:

> Don't reference it unless for the TFMs you target that don't have it implicitly.

Thanks for educating me, I dind't know. Will re-review the PR and get it going soon.

**Comment by abatishchev** [comment]
@thompson-tomo can you please check why the build fails?

**Comment by thompson-tomo** [comment]
@abatishchev have tweaked the conditions which should have resolved the build issue

**Review by abatishchev — DISMISSED** [review]

**Review by abatishchev — APPROVED** [review]

**Comment by abatishchev** [comment]
Awesome, thank you again, @thompson-tomo!

**Comment by abatishchev** [comment]
Published all packages to NuGet.org as `beta1`

**Pull request merged**
