### PR TITLE
RS256 ctor can accept cert with no private key

### PR DESCRIPTION
**Pull request by PureKrome**
- I'm not sure how to create a certificate _without_ a public key. (I would like to test this scenario, if it's doable).
- Included some tests for
  - Certificate has public key only.
  - RS256Algorithm can be created with only a public key (existing code, just adding a simple test).

### CODE REVIEW

**Comment by abatishchev** [comment]
Awesome! Please bump the nuget package version inside JWT.csproj. And it's good to go.

**Comment by PureKrome** [comment]
To what version? (i'm not sure what your versioning / semver rules are etc).

to: `6.1.0-beta1` or `6.1.0`

**Comment by abatishchev** [comment]
Since beta was never published before and based in prior versioning scheme, I'd call it 6.0.0-beta2.

**Comment by PureKrome** [comment]
Currently, it's `6.0.0-beta2` so i'll make it `beta3`

**Comment by PureKrome** [comment]
Out of interest - is there a way to
- create a certificate without a public key? (i'm guessing, nope?)
- test with a certificate that has public/private key. I'm just using the `TestData.PublicKey1 or 2` to test ... is there a way to add in something with a public and private key, to test that?

**Comment by abatishchev** [comment]
Helps with #239

**Pull request merged**
