### PR TITLE
Updating Json.Net to v10, other dev/test dependencies

### PR DESCRIPTION
**Pull request by abatishchev**
Based on #75 discussion.

The most important change: **removed the beta prefix**.

### CODE REVIEW

**Comment by nbarbettini** [comment]
LGTM 👍

**Comment by ericbock** [comment]
It seems like the [.nuspec](https://github.com/jwt-dotnet/jwt/blob/v2/JWT.nuspec#L15) in v2 needs to be updated to account for the newer version of Json.Net. If I use any version of Json.Net prior to 10.0.1 I get: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0

**Comment by abatishchev** [comment]
Versions of Jon.Net from 6x till 10.x are binary backward compatible. So I don't think we need to update the nuspec. Instead please try to add adding assembly binding redirect into your Web/App.config, e.g. from version 0.0.0.0 till 10.0.0.0 to your version, i.e. 6.0.0.0 or 10.0.0.0, etc.

**Comment by ericbock** [comment]
That worked, thanks.

**Pull request merged**
