### PR TITLE
Automated builds with Cake

### PR DESCRIPTION
**Pull request by nbarbettini**
Closes https://github.com/jwt-dotnet/jwt/issues/74

- [x] Automatically build and run tests
- [x] Supports deploying artifacts automatically (can be enabled later)

### CODE REVIEW

**Comment by nbarbettini** [comment]
The next step should be to sign up for AppVeyor (if you haven't already) and turn it on for this repo. If you need help, let me know!

**Comment by abatishchev** [comment]
Yes, please, go ahead, I haven't registered iirc, not for this project definitely.

**Comment by nbarbettini** [comment]
I'm not sure if I can do it, but I'll check.

**Comment by nbarbettini** [comment]
@abatishchev Yeah, since I'm not an owner of the repo, I can't turn it on for the main fork. I can turn it on for my personal fork. It should be pretty simple:

1. Go to https://ci.appveyor.com/
2. Register using Github, authorize it to your Github account
3. Go to Projects, toggle this repo (jwt) on
4. That should be it 😄

**Comment by abatishchev** [comment]
I got this https://ci.appveyor.com/project/abatishchev/jwt/. Should I make any configuration changes?

**Comment by nbarbettini** [comment]
I usually check "Ignore branches without appveyor.yml". Double check that Visual Studio 2017 is selected under Environment. Everything else should be handled by appveyor.yml. You can try kicking off a build manually and see if it works!

**Comment by abatishchev** [comment]
- [x] Skip branches without appveyor.yml
- [x] Build worker image: Visual Studio 2017

**Comment by nbarbettini** [comment]
After #92 that last step will be unnecessary 😄

**Pull request merged**
