### PR TITLE
Fixed bug in HasOnlyOneSecret(), updated tests

### LINKED ISSUE #256: Error signing with certificate
When using

```c#
var cert = new X509Certificate2("c:\\temp\\client.pfx", "<pwd>");

.WithAlgorithm(new RS256Algorithm(cert));
```

I get this error:

>You can't provide more than one secret to use for encoding.   at JWT.Builder.JwtBuilder.EnsureCanEncode()

I cannot understand what the problem is. Wrong certificate?

It works perfect using a static password, with the following:

```c#
.WithAlgorithm(new HMACSHA256Algorithm())
.WithSecret(Program.Configuration.TokenSecret)
```

### PR DESCRIPTION
**Pull request by abatishchev**
Fixes #256 

* Fixed bug in HasOnlyOneSecret()
* Marked JwtBuilder.Build() with error: true
* Forked .NET Core tests into 2.2 and to 3.1
* Bumped version to 6.1.1

### CODE REVIEW

**Comment by abatishchev** [comment]
@stefansolid can you please try the DLL from [this private build](https://abatishchev.visualstudio.com/OpenSource/_build/results?buildId=403&view=results). If it solves your problem, I'll complete the PR and publish the updated version right away.

**Comment by stefansolid** [comment]
Just a quick question, cannot find where to download the DLL-file. A bit new to this so struggling with finding the output from build.

**Comment by abatishchev** [comment]
Yeah, I know, it's not obvious. Click on "1 published" and it'll list the published artifacts - a NuGet package. Download, unzip. Or consume as a package right away.

**Comment by stefansolid** [comment]
Verified now, both generation and validation of tokens build with certificate works fine. Created with private key, verified with public key.

**Comment by stefansolid** [comment]
Might have answered to quickly, the MustVerifySignature() seems to fail when using certificate. It throws SignatureVerificationException when i have created a builder that runs Decode

Creating a JWTBuilder as earlier with cert, creates a token.

GetJwtBuilder().MustVerifySignature().Decode<IDictionary<string, string>>(securityTokenKey)

GetJwtBuilder() returns a JwtBuilder as per "new JwtBuilder().WithAlgorithm(new RS256Algorithm(cert))"

As far as I can see, there is thrown "'System.ArgumentNullException' in JWT.dll" when I add the MustVerifySignature() to builder. Is there any internal checks for "secret-string" or similar?

**Comment by abatishchev** [comment]
I think it's another bug, I'll take a look.

**Comment by abatishchev** [comment]
Please [see here](https://github.com/jwt-dotnet/jwt/blob/571b8866a3ffe014aa1e075f22d44d85b451b92c/tests/JWT.Tests.Core3/JwtBuilderEncodeTests.NetCore3.cs#L47) what worked for me.

**Comment by abatishchev** [comment]
Wait, putting "random" into secret also works. Let me complete this PR and change that in another

**Comment by abatishchev** [comment]
[Released](https://github.com/jwt-dotnet/jwt/releases/tag/20200324.2)!

**Pull request merged**
