### PR TITLE
Add support for nbf (Not Before) token claim validation in V2

### PR DESCRIPTION
**Pull request by abatishchev**
Redoing https://github.com/jwt-dotnet/jwt/pull/37

### CODE REVIEW

**Comment by abatishchev** [comment]
@jhurdlow, @nbarbettini please take a look

**Comment by jhurdlow** [comment]
Looks like the 'nbf' will never be checked if 'exp' doesn't exist. 'nbf' should still be checked in that case.

**Comment by abatishchev** [comment]
Yes, I found that too (tests failed) so I reworked that part.

**Comment by abatishchev** [comment]
@jhurdlow can you please take a look once again?

**Comment by abatishchev** [comment]
Pushed to NuGet as [2.3.0-beta](https://www.nuget.org/packages/JWT/2.3.0-beta). Thanks you both!

**Pull request merged**
