### PR TITLE
OWASP Security Tests and Fixes

### PR DESCRIPTION
**Pull request by bjnoelucanr**
Added security tests based on [OWASP JWT recommendations](https://www.owasp.org/index.php/JSON_Web_Token_(JWT)_Cheat_Sheet_for_Java). 

Found and fixed a vulnerability allowing an attacker to create a HMAC Token for an RSA Decoder.

The fix is in two places.
- JwtDecoder - set _algFactory to default when algorithm factory is not passed in.
- RSAFactory - can only use RSA algorithms.

Resources on the Vulnerabilities:
[OWASP JWT Recommendations](https://www.owasp.org/index.php/JSON_Web_Token_(JWT)_Cheat_Sheet_for_Java)
[JWT Critical Vulnerabilities](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/)
[JWT Token Editor](https://jwt.io/)

### CODE REVIEW

**Comment by abatishchev** [comment]
Thanks a lot for these changes!

**Comment by abatishchev** [comment]
@bjnoelucanr can you please come back on this and address review suggestions?

**Comment by bjnoelucanr** [comment]
@abatishchev which suggestions are you referring to?

**Comment by abatishchev** [comment]
Please see my comments above

**Comment by bjnoelucanr** [comment]
@abatishchev Sorry, I don't see any review suggestions in this thread or attached to the code.

**Comment by bjnoelucanr** [comment]
Yes, got it! Thanks!

**Comment by abatishchev** [comment]
@nbarbettini Nate, do you know why AppVeyor might not report the status back so I can't merge the pr?

**Comment by nbarbettini** [comment]
Weird - might be a temporary glitch? You can try logging into AppVeyor and manually restarting the build for this commit. That might get it going again.

**Comment by abatishchev** [comment]
It happens all the time, unfortunately. To me looks like an issue of integration between GH and AV. Re-triggered both builds, let's see how it'll go.

**Comment by abatishchev** [comment]
Per [this thread](http://help.appveyor.com/discussions/problems/3644-pull-request-status-on-github-shows-three-appveyor-status-first-one-stays-on-yellow-forever), stooped requiring 'branch', only 'pr.

**Pull request merged**
