### PR TITLE
Add support for using SHA384 and SHA512 hashing algorithms with RSASSA-PKCS1-v1_5

### PR DESCRIPTION
**Pull request by simon-pearson**
An initial stab at half of the work captured in issue #304 .  I figure it'll be easier to tackle this issue in two separate PRs; one adding support for using SHA384 and SHA512 hashing algorithms with RSASSA-PKCS1-v1_5, and another for adding support for the ECDSA algorithms.  This PR covers using SHA384 and SHA512 hashing algorithms with RSASSA-PKCS1-v1_5.

This is just a starting point to set the ball rolling; I'm not at all precious about any of this code and will happily make any suggested changes.

### CODE REVIEW

**Comment by abatishchev** [comment]
Awesome. Thank you so much, @simon-pearson! I took a liberty and made few code style changes.

I bumped the version to 8.0.0 due to a breaking change in the interface. Or should we have bump it just to 7.4.0?

And before releasing - should we make it `beta` or you're confident in the changes? I personally feel it'd ok to release without a beta period.

**Comment by abatishchev** [comment]
Sorry for messing up with your PR but I didn't manage to make GitHub Actions to work with a fork :(
I carefully examined https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/, tried all kinds of settings but still.

**Comment by simon-pearson** [comment]
> Awesome. Thank you so much, @simon-pearson! I took a liberty and made few code style changes.
> 
> I bumped the version to 8.0.0 due to a breaking change in the interface. Or should we have bump it just to 7.4.0?
> 
> And before releasing - should we make it `beta` or you're confident in the changes? I personally feel it'd ok to release without a beta period.

Alexander, I'll leave it to you to make the final call on the versioning and whether to have a beta period 🙂

**Comment by abatishchev** [comment]
Pushed to nuget as [8.0.0](https://www.nuget.org/packages/JWT/8.0.0), please give it a try.

**Pull request merged**
