### PR TITLE
Adding support of AppVeyor to v2 branch

### PR DESCRIPTION
**Pull request by abatishchev**
Cherry-picking Cake/AppVeyor related commits from master to v2.

### CODE REVIEW

**Comment by abatishchev** [comment]
@nbarbettini do you know is it possible to reuse existing yml to make it working with non-Core project structure from v2 branch?

**Comment by abatishchev** [comment]
@nbarbettini never mind, apparently I've managed it to get working

**Comment by abatishchev** [comment]
@nbarbettini please review/approve

**Comment by abatishchev** [comment]
Thank you, sir!

**Comment by abatishchev** [comment]
@nbarbettini can you please help to properly integrate old branch with AppVeyor to push 2.x packages to nuget while 3.x is in beta?

**Comment by nbarbettini** [comment]
@abatishchev Any branch that has an `appveyor.yml` file should build on AppVeyor. Pushing 2.x versions to NuGet should work too. You could always build the package locally and then manually update to NuGet, too. Let me know if I'm misunderstanding something here.

**Comment by abatishchev** [comment]
In v3 ​the script looks to artifacts\*.nupkg but in v2 nobody creates the package under that folder. And that's where I don't know how to update the script it to run nuget pack.

**Comment by nbarbettini** [comment]
Ah, I get it now. The quickest thing to do would be to pack and upload manually to NuGet.
It should be possible to run nuget pack from the cake script, but I'd need to take some time to look at it. If you want to do this, assign me on a new issue. 👍

**Comment by abatishchev** [comment]
Yeah, that's what I do right now when back-port anything to v2. And it's so more convenient to press a button in AppVeyor than do everything manually so I was thinking to bring it to v2 as well. But if it isn't that easy from top of your head then let's just give up :)

**Comment by nbarbettini** [comment]
It should be easy, my brain is just full of other things right now 😉 I may not be able to work on it right away, but I can definitely take a look. Once it's set up for CD it's so hard to go back!

**Pull request merged**
