### PR TITLE
Make a copy of extra headers before modifying them

### LINKED ISSUE #225: Fix for issue 206 introduced dictionary modification
"extraHeaders" is passed to Encode.
Encode() used to copy this dictionary, not it keeps a reference to it and modifies it.

### PR DESCRIPTION
**Pull request by jporkka**
Resolves #225, #222.

### CODE REVIEW

**Comment by abatishchev** [comment]
Please bump the version in JWT.csproj so I can release it right away

**Comment by jporkka** [comment]
Bump to what?
Current version is 5.3.0-beta2

**Comment by abatishchev** [comment]
5.3.1 please. I don't think this change requires a stage/beta. If you feel otherwise keep it in beta then.

**Comment by jporkka** [comment]
thanks

**Comment by abatishchev** [comment]
You're welcome!

**Pull request merged**
