### PR TITLE
Make AddCalims accept an IReadOnlyDictionary

### PR DESCRIPTION
**Pull request by IvaYan**
The `AddClaims()` method does not modify the payload in any way. We can use `IReadOnlyDictionary` instead of ordinary `IDictionary`.

### CODE REVIEW

**Comment by abatishchev** [comment]
Hi! I'm happy to make this change.
But first can you please explain what's the issue right now: does it work or not; if yes then does it misbehave or what?

**Comment by IvaYan** [comment]
Hi!
Everything works fine and behaves as expected, but to me it seems odd that we pass a mutable dictionary in order to simply read its content.

For example, we may have an `AccessToken` class like this:

```C#
class AccessToken {
    public IReadOnlyDictionary<string, object> Payload {get;}
}
```

This class manages its state internally, so it exposes the payload as a read-only dictionary so that others can't modify it. With the current implementation we can't use it like this
```C#
var encodedToken = new JwtBuilder()
                .WithAlgorithm(new HMACSHA256Algorithm())
                .WithSecret(Secret)
                .AddClaims(Payload)
                .Build();
```
because `AddClaims()` does not accept `IReadOnlyDictionary`.

**Comment by abatishchev** [comment]
Sure, it makes sense to pass something more lightweight. Would `IEnumerable<KeyValuePair<K,V>>` work/work better here?

**Comment by IvaYan** [comment]
Yeah, I agree, `IEnumerable` fits even better here. Shall I start another pull request?

**Comment by abatishchev** [comment]
I'd just edit this PR. And please bump the version in JWT.csproj to 6.0.1 so I'll publish it right away.

**Comment by IvaYan** [comment]
Done.

**Comment by abatishchev** [comment]
Sorry, please change only Version, other should stay 6.0.0.0 (simplifies many upgrade and debug scenarios).

**Comment by abatishchev** [comment]
Yay, thanks for the contribution! I'll publish it shortly.

**Pull request merged**
