### PR TITLE
Updated ES, ECDSA algorithms with directive to include into .NET 5.0

### PR DESCRIPTION
**Pull request by abatishchev**

### CODE REVIEW

**Comment by abatishchev** [comment]
@iPilot can you please try the package from this build: https://abatishchev.visualstudio.com/OpenSource/_build/results?buildId=793&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by abatishchev** [comment]
@iPilot ping on to try out this private build to make sure it works now.

**Comment by iPilot** [comment]
I had to spend some time for understanding local nuget packages source. With 8.2.3 project still not compiles.

**Comment by abatishchev** [comment]
@iPilot indeed! please try this one: https://abatishchev.visualstudio.com/OpenSource/_build/results?buildId=802&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by iPilot** [comment]
Ok, it works now.

**Comment by abatishchev** [comment]
Sweet! Will push to NuGet shortly.

**Pull request merged**
